"""Create sessions and conversations tables

Revision ID: 2d5e4de0ec4f
Revises: 
Create Date: 2025-07-19 07:22:42.899581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d5e4de0ec4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('conversation_number', sa.Integer(), nullable=False),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.Column('analysis_type', sa.String(length=20), nullable=False),
    sa.Column('advice', sa.Text(), nullable=True),
    sa.Column('speechflaws', sa.Text(), nullable=True),
    sa.Column('nuanceinquiry', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('alternativeexpressions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('suggestion', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversations')
    op.drop_table('sessions')
    # ### end Alembic commands ###
