"""Add name column to sessions table

Revision ID: 9506d8a9ca8e
Revises: 2d5e4de0ec4f
Create Date: 2025-07-19 07:43:03.558977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9506d8a9ca8e'
down_revision: Union[str, Sequence[str], None] = '2d5e4de0ec4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('name', sa.String(length=100), nullable=True))
    op.drop_column('sessions', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_column('sessions', 'name')
    # ### end Alembic commands ###
